# Generated by Django 5.0.6 on 2024-05-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("level", models.CharField(max_length=50)),
                ("salary", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("офис", "Офис"),
                            ("дом", "Дом"),
                            ("свалка", "Свалка"),
                        ],
                        default="офис",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("number", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=100)),
                ("requirements", models.TextField()),
                ("offer", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открытая"), ("close", "Закрытая")],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "vacancies",
                "ordering": ("name",),
            },
        ),
    ]
