# Generated by Django 5.0.6 on 2024-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0002_alter_vacancy_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="name",
            new_name="position",
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
