# Generated by Django 5.0.6 on 2024-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0003_rename_name_vacancy_position_alter_vacancy_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
