# Generated by Django 5.0.6 on 2024-06-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0005_category_vacancy_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancy.category",
            ),
        ),
    ]
